import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll'>
          <h1 className='text-[3rem] lg:text-[5rem] md:text-[5rem] font-extrabold text-gray-700'>
            Read{' '}
            <Link href='/posts/first-post'>
              <a className='text-purple-300 hover:text-purple-200'>
                this page!
              </a>
            </Link>
          </h1>
          <p className='text-2xl text-gray-700'>
            Get started by editing <code>pages/index.js</code>
          </p>

          <div className='grid grid-cols-1 grid-rows-3 lg:grid-rows-2 md:grid-rows-2 justify-center items-center lg:grid-cols-2 md:grid-cols-2 gap-3 mt-3 pt-3 w-full lg:w-2/3 md:w-full'>
            <div className='hover:scale-105 cursor-pointer duration-500 flex flex-col justify-center items-center text-center rounded shadow-xl border-2 border-gray-500 h-full w-full p-6'>
              <a href='https://nextjs.org/docs'>
                <h2 className='text-lg text-gray-700'>Documentation &rarr;</h2>
                <p className='text-sm text-gray-600'>
                  Find in-depth information about Next.js features and API.
                </p>
              </a>
            </div>
            <div className='hover:scale-105 cursor-pointer duration-500 flex flex-col justify-center items-center text-center rounded shadow-xl border-2 border-gray-500 h-full w-full p-6'>
              <a href='https://nextjs.org/learn' className=''>
                <h2 className='text-lg text-gray-700'>Learn &rarr;</h2>
                <p className='text-sm text-gray-600'>
                  Learn about Next.js in an interactive course with quizzes!
                </p>
              </a>
            </div>
            <div className='hover:scale-105 cursor-pointer duration-500 flex flex-col justify-center items-center text-center rounded shadow-xl border-2 border-gray-500 h-full w-full p-6'>
              <a
                href='https://github.com/vercel/next.js/tree/canary/examples'
                className=''
              >
                <h2 className='text-lg text-gray-700'>Examples &rarr;</h2>
                <p className='text-sm text-gray-600'>
                  Discover and deploy boilerplate example Next.js projects.
                </p>
              </a>
            </div>
            <div className='hover:scale-105 cursor-pointer duration-500 flex flex-col justify-center items-center text-center rounded shadow-xl border-2 border-gray-500 h-full w-full p-6'>
              <a
                href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                className=''
              >
                <h2 className='text-lg text-gray-700'>Deploy &rarr;</h2>
                <p className='text-sm text-gray-600'>
                  Instantly deploy your Next.js site to a public URL with
                  Vercel.
                </p>
              </a>
            </div>
          </div>
        </div>
      </main>
      <footer className=''>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className=''>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};

export default Home;
